### PR TITLE
HQ-1070 Fix placement of npm preperation

### PR DESCRIPTION
**Pull request by danpoltawski**
Previously we were preparing it before we'd cleaned up the branch

### CODE REVIEW

**Comment by stronk7** [comment]
thanks! Merged and copied also to laptop.

**Comment by dmonllao** [comment]
I've added a commit for the errors caused by the unaborted previous rebase.

1bcb48885921ba65d179c1e8edb2ce2d45b1fb5a

**Comment by dmonllao** [comment]
https://github.com/dmonllao/moodle-local_ci/compare/hq-1070-abort-rebase

**Comment by danpoltawski** [comment]
Created #88 @dmonllao

**Pull request merged**
