### PR TITLE
Bump to PHPCS 2.9.2

### PR DESCRIPTION
**Pull request by stronk7**
To use https://github.com/moodlehq/moodle-local_codechecker/pull/51

(once it has been merged, not before, of course!) ;-)

### CODE REVIEW

**Comment by stronk7** [comment]
Grrr, there are still randoms happening... look to:

https://travis-ci.org/moodlehq/moodle-local_ci/jobs/479949329

Will look after this if there are more place where we should be applying the ordering...

**Comment by stronk7** [comment]
Ok, sorting amended to use some better attributes (initial line, final line, rule, weight...)... let's see.

**Comment by andrewnicols** [comment]
Looks good apart from the Travis fail. Merging anyway since the travis fail looks unrelated.

**Comment by stronk7** [comment]
> Looks good apart from the Travis fail. Merging anyway since the travis fail looks unrelated.

Yeah, it started failing (java installation) recently... let's see if it's consistent and we need to move to openjkd or so... or just a temporal glitch... tests are passing locally (but a couple of remaining fixtures to fix for the new ordering).

Thanks!

**Pull request merged**
