### PR TITLE
MDLSITE-4625 Report grunt errors in the prechecker

### PR DESCRIPTION
**Pull request by danpoltawski**
Previously the prechecker was only reporting on undetected changes in files from grunt. This makes it report on grunt failures.

### CODE REVIEW

**Comment by stronk7** [comment]
Only point I can imagine is that "GRUNT-CHANGE" output comes also with an "ERROR: Some modules are not properly ..." line that now will be reported, together with the changes and previously was not. I've seen you've adapted that in the tests. If you think it's ok enough, I'm happy.

**Comment by danpoltawski** [comment]
> Only point I can imagine is that "GRUNT-CHANGE" output comes also with an "ERROR: Some modules are not properly ..." line that now will be reported, together with the changes and previously was not. 

I think thats good, no?

**Comment by stronk7** [comment]
I'm not sure if it's good (not saying it's bad either, heh). Just it's like a redundant error when after it the detailed (GRUNT-CHANGE) cases (with file...) come.

**Comment by stronk7** [comment]
There are 2 alternative:

- or we leave it as is. And the generic, colon terminated error is shown before the GRUNT-CHANGE occurrences.
- or we change it to "PROBLEM" and then it's not reported (because the GRUNT-CHANGE occurrences are enough).

I'm happy with both.

**Comment by danpoltawski** [comment]
For me if grunt is failing, that is **more important** to display the real error from grnt than the GRUNT-CHANGE (which is just a report of the final outcome). So I think its fine to have both.

**Comment by stronk7** [comment]
Oki, merging then...

**Pull request merged**
