### PR TITLE
MDLSITE-5003 - switch to using local validator

### PR DESCRIPTION
**Pull request by danpoltawski**
Building on Mark's work in #174 (I would do it on that pull request if I could collaborate on it)

### CODE REVIEW

**Comment by danpoltawski** [comment]
Okay, this branch now ready for merging once travis gives the green light.

**Comment by mrmark** [comment]
Looks great!

**Comment by stronk7** [comment]
I'm checking we have Java 8 in our CIs... heh... will be giving this a run into some (laptop) of them and merge upstream... thanks!

Proceeding...

**Comment by danpoltawski** [comment]
ping

**Comment by mrmark** [comment]
@stronk7 since you are testing out CI stuffs, would you want to do https://github.com/moodlehq/moodle-local_codechecker/pull/40 at the same time?  If not, no worries, don't want to hold this up as it is much more important.  Cheers!

**Comment by stronk7** [comment]
Sorry guys, trapped wit meetings, chats, discussions. Have come here twice but had to leave. Promised today (<8h) this will done. If not, you both are invited to come to my village festivals and drink as much delicious wine as you want. Promised! Seriously, soz!

**Comment by stronk7** [comment]
Merged (with a tiny whitespace fix in the merge). Spread to master and laptop branchs, going to configure the jobs to `npm install` on site upgrade and done.

Closing this, thanks!

**Comment by danpoltawski** [comment]
Damn, I almost booked the flights

**Comment by stronk7** [comment]
you're welcome!

**Comment by mrmark** [comment]
Thanks @stronk7 !

**Comment by mrmark** [comment]
Oh and thanks @danpoltawski for fully implementing it! Cheers guys!

**Comment by stronk7** [comment]
Of course, NO thanks to you @mrmark !
(joking, of course. Thanks heaps!)

**Pull request merged**
