### PR TITLE
MDLSITE-4722 ci: compare_databases php improvements

### PR DESCRIPTION
**Pull request by stronk7**
The PHP job was really outdated and it was not following the
database_column_info specs properly, leading to both PHP Notices
and innacurate differences output.

This PR just introspects database_column_info via reflection to
get the correct list of properties to compare, moving from old
array/stdclass approach.

Note I've not added yet tests for it, but needed this fixed to be able to change/test the shell script in a reliable way. This change is only php. And differences in results are obvious:

From:

````
Problems found comparing databases!
  Parameters: dbhost1=localhost, dbhost2=localhost, dblibrary=native, dbname1=ci_installed_31585_31585, dbname2=ci_upgraded_31585_31585, dbprefix1=cii_, dbprefix2=ciu_, dbtype=mysqli, dbuser1=stronk7, dbuser2=stronk7
  Number of errors: 1

  Column completionstatusallscos of table scorm difference found in *data: Array !== Array
````

To:

````
Problems found comparing databases!
  Parameters: dbhost1=localhost, dbhost2=localhost, dblibrary=native, dbname1=ci_installed_31585_31585, dbname2=ci_upgraded_31585_31585, dbprefix1=cii_, dbprefix2=ciu_, dbtype=mysqli, dbuser1=stronk7, dbuser2=stronk7
  Number of errors: 3

  Column completionstatusallscos of table scorm difference found in not_null: false !== true
  Column completionstatusallscos of table scorm difference found in has_default: false !== true
  Column completionstatusallscos of table scorm difference found in default_value: null !== 0
````

### CODE REVIEW

**Comment by danpoltawski** [comment]
Doing a basic regression test http://ci.stronk7.com/view/master/job/25.%20Compare%20installed-upgraded%20DB%20from%2027_STABLE%20(master)/3655/console

**Comment by danpoltawski** [comment]
Merged, thanks!

**Comment by stronk7** [comment]
hah!

**Comment by stronk7** [comment]
just was watching and happened!

**Comment by stronk7** [comment]
thanks!

**Pull request merged**
