### PR TITLE
MDLSITE-4017: Prevent mustfix fixfor version to be deleted on reopen

### PR DESCRIPTION
**Pull request by stronk7**
- Already tested @ https://tracker.moodle.org/browse/MDL-53820, both with and without mustfix version.
- Amended [Docs](https://docs.moodle.org/dev/index.php?title=Release_process&type=revision&diff=49806&oldid=49645) to keep the parameter updated in CI servers.
- Public server [already contains](http://integration.moodle.org/view/tracker/job/Tracker%20-%20CI%20-%20Move%20reopened%20out%20from%20current/44995/parameters/) the new parameter, ready for an auto-update once/if this is merged.

Ciao :-)

### CODE REVIEW

**Comment by stronk7** [comment]
As far as it was tested, and wanting to have it in production server ASAP, to avoid the mustfix deletion to happen... I'm merging this myself.

Ciao :-)

**Comment by stronk7** [comment]
Merged, thanks Eloy!

**Comment by stronk7** [comment]
Pleasure, thanks!

**Comment by scara** [comment]
LOL :laughing:

**Comment by stronk7** [comment]
It's soo boring, without that, heh!

**Pull request merged**
