### PR TITLE
travis/check_branch_status.php: remove moodle depdency

### PR DESCRIPTION
**Pull request by danpoltawski**
* Add bats test for script
* Import clilib from Moodle (will be useful for various other scripts)
* Remove moodle requirement from script

### CODE REVIEW

**Comment by danpoltawski** [comment]
I don't _love_ these remote tests that much, but I think it should be safe enough.

**Comment by stronk7** [comment]
Uhm... just saw that we still have a number of dependencies of that clilib out there:

````php
$ ag CFG
check_upgrade_savepoints/savepoints2checkstyle.php
36:require_once($CFG->libdir.'/clilib.php');      // cli only functions

compare_databases/compare_databases.php
38:require_once($CFG->libdir.'/clilib.php');      // cli only functions
100:$CFG->debug = DEBUG_DEVELOPER;
101:error_reporting($CFG->debug);
280:    global $CFG;
283:    if (!file_exists("$CFG->libdir/dml/$classname.php")) {
286:    require_once("$CFG->libdir/dml/$classname.php");

generate_component_ant_files/generate_component_ant_files.php
37:require_once($CFG->libdir.'/clilib.php');      // cli only functions

diff_extract_changes/diff_extract_changes.php
39:require_once($CFG->libdir.'/clilib.php');      // cli only functions

initial_jenkins_moodle_setup/initial_jenkins_moodle_setup.sh
33:#   - moodlewwwroot: $CFG->wwwroot of the Moodle site.

list_valid_components/list_valid_components.php
97:    unset($CFG);
98:    global $CFG;
99:    $CFG = new stdClass();
100:    $CFG->dirroot = $options['basedir'];
101:    $CFG->libdir = $CFG->dirroot . '/lib';
102:    $CFG->admin = 'admin';
103:    require_once($CFG->dirroot . '/lib/classes/component.php');
162:            $pluginpath = str_replace($CFG->dirroot . '/', '', $pluginpath);
165:            $pluginpath = str_replace($CFG->dirroot, $options['basedir'] , $pluginpath);
188:            $subsystempath = str_replace($CFG->dirroot . '/', '', $subsystempath);
191:            $subsystempath = str_replace($CFG->dirroot, $options['basedir'], $subsystempath);

remote_branch_checker/checkstyle_converter.php
35:require_once($CFG->libdir.'/clilib.php');      // cli only functions

run_phpunittests/config.php.template
3:unset($CFG);
4:global $CFG;
5:$CFG = new stdClass();
8:$CFG->wwwroot   = 'http://localhost';
9:$CFG->admin     = 'admin';
10:$CFG->directorypermissions = 00777;
11:$CFG->dataroot='%%DATADIR%%';
14:$CFG->dblibrary='%%DBLIBRARY%%';
15:$CFG->dbtype='%%DBTYPE%%';
16:$CFG->dbhost='%%DBHOST%%';
17:$CFG->dbuser='%%DBUSER%%';
18:$CFG->dbpass='%%DBPASS%%';
19:$CFG->dbname='%%DBNAME%%';
20:$CFG->dboptions=array();
23:$CFG->phpunit_prefix='p_';
24:$CFG->phpunit_dataroot='%%DATADIRPHPUNIT%%';
30:$CFG->debug = E_ALL | E_STRICT;
31:$CFG->xmlstrictheaders = false;
32:$CFG->debugdisplay = true;
33:$CFG->perfdebug = 15;
35:$CFG->upgradeshowsql = true;
36:$CFG->debugpageinfo  = true;
39:$CFG->earlyprofilingenabled = true;
40:$CFG->profilingautofrec = 10;
41:$CFG->profilingincluded = '/*view.php,/*index.php';
42:$CFG->profilingallowme = true;
43:$CFG->profilingallowall = true;
46:$CFG->langstringcache = false;
49:$CFG->noemailever = true;
52:$CFG->enablecompletion = true;
53:$CFG->enableavailability = true;
54:$CFG->usetags = true;
55:$CFG->enableoutcomes = true;
56:$CFG->usecomments = true;

remote_branch_checker/remote_branch_reporter.php
39:require_once($CFG->libdir.'/clilib.php');      // cli only functions
40:require_once($CFG->dirroot.'/local/ci/remote_branch_checker/lib.php');

tests/fixtures/31-merge-conflict.patch
48:+        global $CFG, $USER, $DB;
49:+        require_once($CFG->dirroot . "/user/lib.php");

tests/fixtures/31-whitespace-error.patch
18: unset($CFG);  // Ignore this line
19:-global $CFG;  // This is necessary here for PHPUnit execution
20:+global $CFG;  // This is necessary here for PHPUnit execution 
21: $CFG = new stdClass();

travis/check_branch_status.php
28:require_once($CFG->libdir.'/clilib.php');      // cli only functions
29:require_once($CFG->libdir.'/filelib.php');      // cli only functions

verify_commit_messages/commits2checkstyle.php
36:require_once($CFG->libdir.'/clilib.php');      // cli only functions
````

Maybe we should create a proper issue and fix all them now that we are  "importing" clilib to local_ci?

**Comment by danpoltawski** [comment]
Well, I was working on that - but why do them all at once? I was doing one at a time, with tests as I add them?

**Comment by danpoltawski** [comment]
(The ultimate goal being prechecker without Moodle - which I think is achievable for everything but phpdocs checker)

**Comment by stronk7** [comment]
Agree, thanks!

**Comment by danpoltawski** [comment]
Note: I just pushed a quick commenting out of the checking of build status test.. Because it'll lead to any failure causing travis to fail forever.

**Comment by stronk7** [comment]
Aha, I see a3b619d . It consumes itself, heh. Thanks!

**Pull request merged**
