### PR TITLE
MDLSITE-4211 testing: add ci tests to local_ci

### PR DESCRIPTION
**Pull request by danpoltawski**
Adds some coverage to:
* grunt_process
* less_checker
* php_lint
* shifter_walk
* thirdparty_check

### CODE REVIEW

**Comment by danpoltawski** [comment]
I am a bit 'down' on bats, even thought it seems a travis specific issue (it's hard to tell) https://github.com/sstephenson/bats/issues/150

**Comment by danpoltawski** [comment]
Now i've sorted out the annoying travis problem, i'm sending this for integration proper

**Comment by danpoltawski** [comment]
Note that I don't "love" that we have to do a whole git clone of moodle.git in the traivs job (seems slow an inefficient). But:
* We need multiple branches, so a shallow clone is complex/tricky to achieve
* Caching the moodle.git dir is not really much better because its a big directory and travis [store it on the network anyway](https://docs.travis-ci.com/user/caching/#How-does-the-caching-work%3F)
* It is surprisingly fast (1min) and we don't build that often
* The grunt/shifter tests are are the main time sink

**Comment by stronk7** [comment]
Awesome stuff!

**Comment by Hannahmarianopigao** [comment]
sorry if imade mestakes.please correct me if i doing budthings.in this site.becouse im in learning
what is better.sorry again.hope.u send email.documents.with my name
thank u.becouse only phone i use for now.but somedah god anwer
i buy things.for my obligation sorry.

**Pull request merged**
