### PR TITLE
Remove old npm stuff forever

### PR DESCRIPTION
**Pull request by stronk7**
This builds on top of #210, because bats (the testing environment) itself has some npm dependencies to install old stuff.

I think we can safely remove them now (once #210 is upstream) and I've created this branch about that:
- Remove the npm dependencies in travis.
- Remove the npm dependencies in bats setup.
- Remove the checks using those tools that we aren't using anymore (csslint, jshint..).
- Adapt all tests to the new status quo.

Obviously, this is failing right now. Will be till everything above is fixed.

### CODE REVIEW

**Comment by andrewnicols** [comment]
Should we look to land this change?

**Comment by stronk7** [comment]
Buff,

I had this completely forgotten, will try to re-read everything and take a look later today. Thanks for reminding!

Ciao :-)

**Comment by stronk7** [comment]
Hi,

just have done a quick git diff between current master and this PR, and much of it is completely outdated and old: tests have been already updated upstream, travis too... I'll try to come with a new, current, patch soon here.

**Comment by stronk7** [comment]
Side notes:

# We stopped using `jshint` (switched to `eslint`) for Moodle 3.2 ([MDL-54889](https://tracker.moodle.org/browse/MDL-54889)). YUI/Shifter internal use apart!
# We stopped using `csslint` (switched to `stylelint`) with Moodle 3.2 too ([MDL-55372](https://tracker.moodle.org/browse/MDL-55372]).

**Comment by stronk7** [comment]
Reopening because I closed this by mistake with my last comment. I'm working on a patch removing the nodejs old dependencies and bumping all the tests to work against newer core branches.

**Comment by stronk7** [comment]
Ok, I think we can consider now this ready. Each commit, they are 7 is self-explanatory.

The main/biggest ones being those removing csslint and jshint completely, then dependencies, tests and other small things.

About the tests, I've bump a bunch of them, specially the CiBoT ones to use current (39_STABLE and up) branches, because we were testing it with really old stuff.

The changes also served to detect a bug in core with MySQL 8.0 ([MDL-75856](https://tracker.moodle.org/browse/MDL-75856)), so good thing we bumped also travis environment to more actual one.

Ciao :-)

**Pull request merged**
