### PR TITLE
MDLSITE-4625 take #2 : Don't show the "heading error", detailed changes are better

### PR DESCRIPTION
**Pull request by stronk7**
This is a followup of #158 , where we started to report "ERROR". But there was an "ERROR" that was just the heading for the "GRUNT-CHANGE" problems reported.

This is about to change the ERROR to WARN so it's not reported anymore, because GRUNT-CHANGE are enough and better (detailed).

This also fixes a minor recurrent warning with recent gnu find versions. An of course amends related tests.

Ciao :-)

### CODE REVIEW

**Comment by danpoltawski** [comment]
Merged, thanks Eloy!

**Comment by danpoltawski** [comment]
Urm https://travis-ci.org/moodlehq/moodle-local_ci/builds/178544130

**Comment by danpoltawski** [comment]
Really weird, passes here locally (and clearly did on travis before too)

**Comment by stronk7** [comment]
Plus I don't think we changed anything there (the failure happens in a grunt warning, not error). Maybe coincidence? Hate the unknown.

**Comment by danpoltawski** [comment]
Something is screwy, it failed again: https://travis-ci.org/moodlehq/moodle-local_ci/builds/178544911

**Comment by stronk7** [comment]
But now it's different test (old branch, vs all possible checks)! Is it possible some concurrence problem is happening (between jobs?). I always imagined they run 100% isolated but...

**Pull request merged**
