### PR TITLE
Simplify output

### PR DESCRIPTION
**Pull request by danpoltawski**
Based on #123 - i'm envisaging adding  tests or doing more work on the output..

### CODE REVIEW

**Comment by stronk7** [comment]
This became out of sync with #123, it seems.

**Comment by danpoltawski** [comment]
rebased (and fixed the bug adding the remote detected by travis)

**Comment by stronk7** [comment]
All right, just 2 comments:

1) I've triple verified the patch and cannot find anything explaining the meaning of your "fixed the bug adding the remote detected by travis". Maybe there is a missing change somewhere? Or maybe I'm blind.

2) Not important at all, but maybe I'd add an "Info: Calculating excluded files" before [#262](https://github.com/moodlehq/moodle-local_ci/pull/124/files#diff-df674db92bac52c259f41ab98ec9b987R262)".

Feel free to self-merge this once 1) and 2) are clarified/considered.. TIA!

**Comment by danpoltawski** [comment]
> 1) I've triple verified the patch and cannot find anything explaining the meaning of you

I've squashed this change, but it was a bug I introduced in the patch by adding `-q` to `git remote add`. It [was detected by travis build.](https://travis-ci.org/moodlehq/moodle-local_ci/builds/150071316#L309)

> 2) Not important at all, but maybe I'd add an "Info: Calculating excluded files"

I've done that and added some more info messages so we better know whats going on in cc893ac

I'll wait for tests then merge this

**Comment by danpoltawski** [comment]
Hmm, the npm stuff isn't being properly redirected: 
http://ci.stronk7.com/job/Precheck%20remote%20branch/1733/console

**Comment by danpoltawski** [comment]
I added  https://github.com/moodlehq/moodle-local_ci/commit/31fd665d72060096192c9c8272d941b807888768 and now working right:
http://ci.stronk7.com/view/prehecker/job/Precheck%20remote%20branch/1734/console

**Comment by danpoltawski** [comment]
https://integration.moodle.org/job/Precheck%20remote%20branch/26106/console

**Pull request merged**
