### PR TITLE
Rewrite unauthenticated github URLs to use https

### PR DESCRIPTION
**Pull request by andrewnicols**
See https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
for more information on this change

### CODE REVIEW

**Comment by andrewnicols** [comment]
Travis is causing us issues here, but the relevant test is passing:
https://app.travis-ci.com/github/moodlehq/moodle-local_ci/jobs/546187397#L475

**Comment by stronk7** [comment]
Other than 3 remaining "git://github.com" cases @ `initial_jenkins_moodle_setup/initial_jenkins_moodle_setup.sh` I think this is perfect, thanks!

I'm going to amend the patch to apply those 3 and done.

**Review by stronk7 — APPROVED** [review]
I'm amending it to replace the 3 remaining instances (though that script hardly will be executed ever) and will push changes then.

**Comment by stronk7** [comment]
PR has been merged already, closing this, thanks!

**Pull request closed without merging**
