### PR TITLE
HQ-1070 autoresolve both amd and yui modules

### PR DESCRIPTION
**Pull request by dmonllao**

### CODE REVIEW

**Comment by danpoltawski** [comment]
This branch has conflicts that must be resolved ^

**Comment by dmonllao** [comment]
Branch updated to e03235e4ebf113f6b1a4298c116e5d5a572bf31c, I forgot to rebase on top of upstream.

**Comment by danpoltawski** [comment]
Thanks, David!

**Comment by danpoltawski** [comment]
FYI I just added 925c15481ef7883cd2037e0b1e9c776bb01c0241 because the colour escape sequences annoy me in the output.

**Pull request merged**
