### PR TITLE
MDLSITE-4685: fix detect_conflicts.sh and improve testing infrastructure

### PR DESCRIPTION
**Pull request by danpoltawski**
- Introduce tests for detect_conflicts
- Fix spaces problem in detect_conflicts
- Add some setup tests for gnu tools in use (can fail when my mac isn't setup right)
- Introduce git_apply_fixture and tidy up tests to avoid having to keep cd'ing

### CODE REVIEW

**Comment by stronk7** [comment]
Sorry, silly question... where does OLDPWD come from? I only can it being used but never set.

**Comment by stronk7** [comment]
Ah! It's built-in bash!

**Comment by danpoltawski** [comment]
ya https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html

**Comment by stronk7** [comment]
I like, this, thanks for modernizing the old script and the new git_apply_fixture(). It makes things easier and mistakes-savvy. yay!

**Comment by stronk7** [comment]
Done, cool!

**Pull request merged**
