### PR TITLE
MDLSITE-5007 Fix warnings in check_upgrade_savepoints

### PR DESCRIPTION
**Pull request by sam-moodle**

### CODE REVIEW

**Comment by danpoltawski** [comment]
Thanks @sam-moodle ! Just waiting for travis to give us the 👍

**Comment by sam-moodle** [comment]
Cheers @danpoltawski ! Thanks.

**Comment by danpoltawski** [comment]
I guess we don't have debugging enabled on ci server..


https://integration.moodle.org/view/master/job/04.%20Check%20upgrade%20savepoints%20(master)/6947/artifact/check_upgrade_savepoints_master.txt
https://integration.moodle.org/view/master/job/04.%20Check%20upgrade%20savepoints%20(master)/6947/console

**Comment by danpoltawski** [comment]
Merged, thanks Sam

**Pull request merged**
