### PR TITLE
MDLSITE-4695 prechecker: add ability to push precheck branches to gitlab

### PR DESCRIPTION
**Pull request by danpoltawski**

### CODE REVIEW

**Comment by danpoltawski** [comment]
I've chosen not to fix  MDLSITE-3676 at the same time, but it will straight forward to do

**Comment by stronk7** [comment]
And the tests?

**Comment by stronk7** [comment]
Merged, thanks!

**Comment by danpoltawski** [comment]
The tests for pre-checker are going to be the most critical, but quite a bit to do before that :)

**Pull request merged**
