### PR TITLE
MDLSITE-4704 commit tests: switch to git rev-list

### PR DESCRIPTION
**Pull request by danpoltawski**
It's what we are using in the actual code.

### CODE REVIEW

**Comment by stronk7** [comment]
There is one more occurrence in [the prechecker](https://github.com/stronk7/moodle-local_ci/blob/master/remote_branch_checker/remote_branch_checker.sh#L219). Maybe we should kill that one too? Heh, and add test looking for occurrences in the future?

**Comment by danpoltawski** [comment]
Added a patch for that, not easily testable so here it from a manual test:
```
Info: Pushing precheck branch to remote
Counting objects: 396, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (138/138), done.
Writing objects: 100% (396/396), 87.78 KiB | 0 bytes/s, done.
Total 396 (delta 301), reused 338 (delta 248)
To git@git.in.moodle.com:integration/prechecker.git
 * [new branch]      master_precheck -> MDL-55372-master-master-6bb410c
```

With regard to tests to prevent it, I think that it would be hard to add a test for that because you can name the arguments however you like. But maybe we should be getting rid of all uses of rev-parse because of what you say about rev-list being a porcelain command?

**Comment by stronk7** [comment]
Ah, I was thinking about something static like we did [here](https://github.com/stronk7/moodle-local_ci/blob/master/tests/00-verifications.bats#L15), so any ' --short ' is simply banned in local_ci.

**Comment by stronk7** [comment]
(and I already looked for occurrences of "git rev-parse", the 2 fixed in this PR were the only ones present, unless i'm wrong). So goal achieved.

**Comment by stronk7** [comment]
So,

1) Or we just ban ' --short ' (current PR)
2) Or we ban all ' rev-parse ' uses (or force them to be verified using ````HASH_OR_TAG^{commit}```` ). Surely I prefer complete ban if ' rev-list ' gives us them alredy verified.

**Comment by stronk7** [comment]
(sorry for all the editions, grrr, it seems my brain and my mouse are totally unconnected today)

**Comment by stronk7** [comment]
So are you happy with 1), aka, current patch r(ban ````--short```` and forget).

**Comment by danpoltawski** [comment]
Yes, if we want to do the rest we can do it in a future issue.

**Comment by stronk7** [comment]
merged, thanks!

**Pull request merged**
