### PR TITLE
MDLSITE-4440 verify_commits: check amos commands

### PR DESCRIPTION
**Pull request by danpoltawski**
Uses code from AMOS (but copy and pasted).

### CODE REVIEW

**Comment by stronk7** [comment]
I like this, but the copy/paste code part... just guessing if it wouldn't be better to:

1) have AMOS clone at hand.
2) extend the class using some late binding if needed in base.

That way we'd react immediately to any change in AMOS... opinions?

**Comment by danpoltawski** [comment]
I feel like its overkill - I especially feel like doing it that way would lead it to become potentially fragile for unrelated changes which are going on in amos (which might increase the requirements of the script and so on). I doubt those parsing functions have ever changed in recent years in any case - and I imagine we would be adding more functionality to detect non-matching amos script (I mean I imagine the prechecker would get more parsing powers than amos would).

Note: I would've just copy and pasted the regexps, but I did it this way because I thought there was less change of me getting things wrong and it looked relatively clean to do and also provide some nice informative messages about what would happen. I think i'd rather just switch to the basic regexps instead of pulling AMOS in as a dependency.

Pinging @mudrd8mz

**Comment by mudrd8mz** [comment]
I agree with Dan. Pulling AMOS as a dependency sounds like an overkill. I am pretty sure these regex's won't change in years, if ever. We will sooner have troubles with UNIX timestamps.

But, I realised another important thing. I did not study the attached unit tests well. But please note that AMOS only processes commits that somehow modify some */lang/en/*.php file. So if there is a commit with AMOScript that modifies README.txt only, AMOS would not parse it. If possible, that would be a good precheck, too.

**Comment by mudrd8mz** [comment]
https://github.com/moodlehq/moodle-local_amos/blob/master/cli/parse-core.php#L367-L398

**Comment by stronk7** [comment]
Thanks, I'm happy then.

About to verify that the commit being analyzed does include some lang/en/xxx file, sounds like we could do that by quickly looking/grepping to the ```--stat``` results.

**Comment by danpoltawski** [comment]
This is kind of awkard in where to put it because it sits more on the 'shell' side than the php side. I suppose we could pass a list of changed files to the php, not sure if that a good idea.

`git diff-tree --no-commit-id --name-only -r <commit-sha> | tr '\n' ','`
to do that list

**Comment by danpoltawski** [comment]
I've added some commits [implementing this file deetcion](https://github.com/moodlehq/moodle-local_ci/pull/129/commits/463f659985c425dbf303a876d681cac6993df693)

**Comment by stronk7** [comment]
Seems bad amos script does need amending now, cz the missing lang file problem is getting precedence?

**Comment by danpoltawski** [comment]
Yes, just updated the remote fixture (and rebased this)

**Comment by stronk7** [comment]
Here we go! Let's break the world!

**Pull request merged**
